environment:
  node_pre_gyp_accessKeyId:
    secure: GOBrUyHVMfZSrmsS4I63fC+E3qploEcIuQc/ofuTK5U=

  node_pre_gyp_secretAccessKey:
    secure: QBSKf6NBLUrjkk7ft4H8LyxATdcJ8PmQObKqDgl1qQmT0ju7r3l/D6t8MN2joQqk

  matrix:
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6
    - nodejs_version: 7

platform:
    - x64
    - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm install --global --production npm-windows-upgrade
  - npm-windows-upgrade --npm-version 2.15.9 --no-dns-check --no-prompt
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - IF /I "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - npm install --build-from-source
  - npm test
  - npm ls
  - SET PATH=node_modules\.bin;%PATH%
  - node-pre-gyp package publish


build: off
test: off
deploy: off
